* Lineaire Algebra
** Auteur: Tom Sydney Kerckhove
** Dankwoord
*** Medewerkers
**** Ward Schodts
     Bedankt voor het idee, de fijne samenwerking en de oplossingen.
**** Frederik Goovaerts (14/20)
     Bedankt voor de hulp in verband met de licentie en de oplossingen.
**** Willem Van Onsem
     Bedankt voor de makefile.
**** Thalia K.
     Bedankt voor het nalezen op taalfouten.
**** Andere medewerkers
     Bedankt voor de hulp met de oplossingen.
     - Thomas Dierckx 
     - Nicholas Haesen
     - Egon Okerman
     - Giel Dops
     - Jorik De Waen
     - Tijl Jappens
     - Jari Peeperkorn
     - Haroen Viaene
     - Eline Vrijsen
     - Nick Van den Broeck
*** De Student
    Dank bij voorbaat om de algemene voorwaarden en de licentie na te leven.
** Algemene voorwaarden
   Zoals beschreven in de licentie mag de broncode van het boek verspreid worden, maar *er mag onder geen enkele voorwaarde een gecompileerde versie verspreid worden.*
   Dit boek heeft ook tot doel studenten latex te laten gebruiken. Bovendien bent u zeker dat u steeds de laatste versie hebt als u de broncode zelf compileert.
** Veelgestelde Vragen
*** Wat mag ik nu wel en niet hiermee?
    Je mag de broncode downloaden en compileren voor jezelf, en gebruiken bij het studeren.
    Je mag ook zelf oplossingen insturen door te forken, aanpassingen te maken, en een pull-request te sturen.
    Je mag ook de broncode verspreiden, maar het is interessanter mensen hiernaartoe te wijzen, zodat men de laatste nieuwe broncode krijgt.
    Je mag geen gecompileerde pdf delen met iemand. Een pdf van dit boek in de dropbox zetten is uit den boze.
*** Waarom die laatste voorwaarde?
    Dit lijkt misschien een vreemde voorwaarde, maar bekijk het zo: We hebben hier best veel tijd in gestoken, en je krijgt dit zomaar van ons.
    We willen onze kan zo groot mogelijk maken dat er mensen een handje toesteken, en dat gaat het makkelijkst door naar deze repo te verwijzen, omdat er dan makkelijker een stuk toegevoegd kan worden.
*** Ik heb een fout gevonden, wat nu?
    Het aangenaamste zou zijn dat je ze zelf verbetert en een pull request doet.
    Je kan echter ook gewoon een issue submitten *met de juiste labels*, dan kijken we er zelf naar.
    Hoe meer info je in de beschrijving van het issue zet, hoe sneller we de fout kunnen verbeteren.
*** Hoe compileer ik hiervan een .pdf bestand?
    Als linux gebruiker kan je eenvoudigweg het make commando uitvoeren.
    #+BEGIN_SRC shell
       make
    #+END_SRC
    Je zal ook het textlive-latex-extra pakket nodig hebben, naast een standaard latex installatie.

    Als windows gebruiker zal je MikTex nodig hebben om het bestand te compileren.
    
*** Er staan nog oefeningen in de cursus waarvan er geen oplossing staat in dit boek, waar blijven die?
    Als er nog een oefening ontbreekt, wordt u uitgenodigd om ze te maken en ze toe te voegen.
    Dit boek is nog niet af.
    Helaas zal het waarschijnlijk niet afgewerkt worden door de auteur.
    De auteur hoop dat het boek zal afgewerkt worden door volgende generaties studenten die lineaire algebra volgen.
